version: "3.8"
services:
  karate-test:
    image: karate-test
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./target:/usr/scr/app/target
      - ~/.m2:/root/.m2
    command: mvn test
